config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'popups/show', as: 'popup'
  post 'pages/hard_job'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def hard_job
    HardJob.perform_async
    flash[:answer] = 'смотрим в консольку'
    redirect_to root_path
  end
end

app/controllers/popups_controller.rb
class PopupsController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/popups_helper.rb
module PopupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.haml
%h1 тестовые кнопки
%div{class: "home", data: {controller: "hello"}}
  %p Приветсвуем на стороне браузера 
  %input{data: {hello_target: "name"}}
  %button{data: {action: "click->hello#greet"}} Greet
  %p{data: {hello_target: "output"}}
  
%div{class: "home", data: {controller: "clipboard"}} 
  %p Можно скопировать текст на стороне браузера
  %input{data: {clipboard_target: "source"}}
  %button{data: {action: "click->clipboard#copy"}} Copy
  %p{data: {clipboard_target: "output"}}

%div.home
  %p Тут мы отправляем задачку
  = button_to 'Job', pages_hard_job_path, method: :post
  - if flash[:answer]
    %div
      %p= flash[:answer]

%turbo-frame{id: "popup"}
  = link_to 'Открыть всплывающее окно', popup_path, data: { turbo_frame: 'popup' }

app/views/popups/show.html.haml
%turbo-frame{id: "popup"}
  .modal
    %p Всплывашечка 
    %button{data: {turbo_frame: "popup", action: "turbo:frame-render->popup#close"}} Закрыть